apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: k8s-space
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: amaldevtech/k8s_repo:myapp
          ports:
            - containerPort: 80
