apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: k8s-space
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80           # Service port (inside cluster)
      targetPort: 5000   # Your Flask app's container port
      nodePort: 30027    # Host port exposed via kind config
